[package]
name = "mtzip"
version = "0.5.0"
edition = "2021"
description = "A library to make zip archives with multithreaded compression"
license = "MIT"
repository = "https://github.com/JohnTheCoolingFan/mtzip"
categories = ["compression", "concurrency"]
documentation = "https://docs.rs/mtzip"
authors = ["Jonh The Cooling Fan <ivan8215145640@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["auto-threading"]
auto-threading = ["sysinfo"]

[dependencies]
flate2 = "1.0"
sysinfo = { version = "0.25", optional = true}
