[package]
name = "mtzip"
version = "1.3.0"
edition = "2021"
description = "A library to make zip archives with multithreaded compression"
license = "MIT"
repository = "https://github.com/JohnTheCoolingFan/mtzip"
categories = ["compression", "concurrency"]
documentation = "https://docs.rs/mtzip"
authors = ["Jonh The Cooling Fan <ivan8215145640@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
flate2 = { version = "1.0", default-features = false}

[features]
default = ["rust_backend"]
rust_backend = ["flate2/rust_backend"]
zlib = ["flate2/zlib"]
