[package]
name = "mtzip"
version = "0.2.0"
edition = "2021"
description = "A library to make zip archives with multithreaded compression"
license = "MIT"
repository = "https://github.com/JohnTheCoolingFan/mtzip"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
